### ISSUE TITLE
Please remove _templates folder 

### ISSUE THREAD

**Issue by kai687** [qianniucity/ollama-doc#1]
Hi 👋,

Can you please remove the `source/_templates` folder? 

I assume you cloned the `sphinxawesome-theme` repository including the "docs" folder.

I added web analytics to my docs in the `page.html` and `feedback.html` template.
Since you cloned this, I see requests to my analytics server from this repository. 

If you don't collect your own analytics, can you please delete this folder, 
or comment out the line `templates_path = ["_templates"]` in your `conf.py` file?

This would help me keep my analytics data clean. Thanks!

**Comment by qianniucity** [comment]
Hi ,

Thanks for reaching out regarding the analytics data. I understand your concern and appreciate you bringing it to my attention.

I've taken the necessary steps to address the issue by commenting out the templates_path line in the conf.py file. This will prevent the cloned repository from including your analytics data in its requests.

I also want to take this opportunity to express my appreciation for the sphinxawesome-theme. It's a fantastic theme that has made my documentation look sleek and professional. I've been very impressed with its features and ease of use.

Thank you again for your understanding and for creating such an awesome theme!

**Comment by kai687** [comment]
Thank you for your kind words and fulfilling my request.
